x-shared-env: &shared-environment
    environment:
        DB_CONNECTION: pgsql
        DB_HOST: postgres
        DB_PORT: 5432
        OCR_WEBHOOK_URL: http://web/api/webhooks/ocr
        OCR_API_ENDPOINT: http://ocr_api:5000
        CREATE_EMBEDDING_URL: http://embedding_api:11434/api/embed
        AWS_ENDPOINT: http://minio:9000/

services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "80:80"
        <<: *shared-environment
        depends_on:
           postgres:
               condition: service_healthy

    worker:
        build:
            context: ./web
            dockerfile: Dockerfile
        restart: unless-stopped
        <<: *shared-environment
        depends_on:
            postgres:
                condition: service_healthy
        command: php artisan queue:work

    minio:
        image: quay.io/minio/minio:latest
        container_name: minio-s3
        restart: unless-stopped
        ports:
            - "9000:9000" # S3 API endpoint
            - "9001:9001" # Web Console UI
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: mysecretpassword
        command: server /data --console-address ":9001"
        volumes:
            - miniodata:/data

    createbuckets:
        image: quay.io/minio/mc:latest
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            until (/usr/bin/mc alias set myminio http://minio:9000 admin mysecretpassword); do
              echo 'Waiting for MinIO server to come online...';
              sleep 1;
            done;
            /usr/bin/mc mb --ignore-existing myminio/uploads;
            exit 0;
            "

    postgres:
        image: pgvector/pgvector:pg17
        container_name: postgres-vector
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: vectordb
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d vectordb" ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

    ocr_api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: ocr_api
        restart: unless-stopped
        ports:
            - "5000:5000"
    embedding_api:
        image: ollama/ollama:latest
        container_name: embedding_api
        ports:
            - "8080:11434"
        volumes:
            - ollama_cache:/root/.ollama
        restart: unless-stopped
        entrypoint:
            - /bin/sh
            - -c
            - |
                ollama serve &
                until ollama list > /dev/null 2>&1; do
                  sleep 1
                done
                ollama pull qwen3-embedding:4b
                wait

volumes:
    miniodata:
    pgdata:
    ollama_cache:
